# fly.toml app configuration file generated for patient-firefly-9861 on 2023-08-02T16:09:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patient-firefly-9861"
primary_region = "iad"

[build]

[env]
  PORT = "8080"

[http_service]
  http_checks = [] # added per course instructions
  internal_port = 8080
  force_https = true # not in course instructions
  auto_stop_machines = true # not in course instructions
  auto_start_machines = true # not in course instructions
  min_machines_running = 0 # not in course instructions
  processes = ["app"]

[experimental] # added per course instructions
  auto_rollback = true # added per course instructions